apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: girus
  name: girus
  namespace: strigus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: girus
  template:
    metadata:
      labels:
        app: girus
    spec:
      containers:
      - image: nginx:1.18.0
        name: nginx
