apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
  namespace: strigus
spec:
  containers:
  - image: nginx:1.21.1
    name: giropops
  dnsPolicy: ClusterFirst
  restartPolicy: Always
